### ISSUE TITLE
Parameter Naming

### ISSUE THREAD

**Issue by LukasFehring** [automl-private/hypersweeper#2]
#### Description
In the classes `SMACSweeperConfig`, `HydraSMAC`, `SMACSweeperBackend`, and `SMACSweeper` instances of the other respected classes are created. However, the naming of parameters is not consistent throughout the classes. E.g. the parameter `hydra.sweeper.budget`  is read by the `SMACSweeperBackend` and passed as `n_trials` to `HydraSMAC`.

Additionally, there are multiple different budgets, which are hard to differentiate.

**Comment by TheEimer** [comment]
So this needs to be documented better, agreed, but at least now almost all of the config is directly passed to the optimizer and not parsed top level. You still need to specify either budget or n_trials, but this is not what's passed to e.g. SMAC, these keywords are handled in the optimizers_kwargs and correspond directly to SMAC. Still a not exactly super simple, but at least the overlap is gone.
